version: '3.8'

services:
  users-service:
    build: ./service-users
    ports:
      - "8001:8000"
    depends_on:
      - users-db
    environment:
      - DATABASE_URL=postgresql://user:pass@users-db:5432/users_db

  users-db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: users_db
    volumes:
      - users_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  products-service:
    build: ./service-products
    ports:
      - "8002:8000"
    depends_on:
      - products-db
    environment:
      - DATABASE_URL=mysql://root:root@products-db:3306/products_db

  products-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products_db
    volumes:
      - products_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  users_data:
  products_data:
